/* The accessibility panel's settings for these mockups: written by grapple/kit/a11y/mockup_bundle.py. */
window.GrappleA11y = {
 "prefix": "ss-",
 "features": {
  "listen": true,
  "font": true,
  "guide": true,
  "jump": true
 },
 "root": "main",
 "skip": ".idx, .sr, .cmp__range",
 "chunk": 220,
 "css": "html.ss-a11y-contrast { --stone: #3d3a35; --line: #9a9284; }",
 "labels": {
  "open": "Accessibility",
  "title": "Accessibility settings",
  "close": "Close accessibility settings",
  "text": "Text size",
  "text_0": "Default",
  "text_1": "Large",
  "text_2": "Largest",
  "display": "Reading and display",
  "contrast": "Higher contrast",
  "readable": "Easier-to-read type",
  "spacing": "More space between lines and letters",
  "underline": "Underline all links",
  "focus": "Stronger keyboard focus outline",
  "motion": "Stop animation and background video",
  "font": "Readable font (Atkinson Hyperlegible)",
  "guide": "Reading guide",
  "note": "Saved in this browser only. Your device settings for zoom and reduced motion are respected as well.",
  "reset": "Reset",
  "done": "Done",
  "jump": "Jump to section",
  "listen": "Listen",
  "read": "Read this page",
  "pause": "Pause",
  "resume": "Resume",
  "stop": "Stop",
  "speed": "Speed",
  "slower": "Slower",
  "normal": "Normal",
  "faster": "Faster",
  "reading": "Reading",
  "paused": "Paused",
  "finished": "Finished",
  "stopped": "Stopped",
  "image": "Image"
 },
 "header": ".hdr",
 "tokens": {
  "ink": "var(--ink)",
  "paper": "var(--paper)",
  "text": "var(--ink)",
  "muted": "var(--stone)",
  "line": "var(--line)",
  "display": "var(--display)",
  "body": "var(--body)"
 }
};
